{% set version = "0.6.3" %}
{% set qdldl_version = "0.1.5" %}

package:
  name: osqp
  version: {{ version }}

source:
  - url: https://github.com/osqp/osqp-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3a12a5dcdd69a835724cc3f82a0cfb3b7317f11ae5ba651cacac856ae566fb3c
    patches:
    - patches/0001-Disable-MKL-Tests-on-nonx86.patch     # [not x86_64]
    - patches/0002-use-ninja-universally.patch
    - patches/0003-do-not-rebuild-libosqp-here-use-our-own-builds.patch

  # The following sources are included purely to support the codegen functionality of osqp,
  # which requires copying the sources of osqp and qdldl as data into the package, so that
  # it can be copied and compiled into a standalone library when needed.
  # We cannot even point this to our shared libosqp builds (aside from the fact that the end
  # result would not be standalone anymore), because libosqp in conda-forged is compiled
  # without the `EMBEDDED` symbol being defined, and has a different ABI than what the
  # code generation here requires. FTR, I tried patching it and I believe that substantial
  # changes to src/osqp/codegen/utils.py would be necessary, e.g. to add `status_polish`,
  # which is required by the libosqp type when `EMBEDDED` is not defined, compare:
  # https://github.com/osqp/osqp/blob/v0.6.3/include/types.h#L71-L73
  - url: https://github.com/oxfordcontrol/osqp/archive/v{{ version }}.tar.gz
    sha256: a6b4148019001f87489c27232e2bdbac37c94f38fa37c1b4ee11eaa5654756d2
    folder: osqp_sources
  - url: https://github.com/oxfordcontrol/qdldl/archive/v{{ qdldl_version }}.tar.gz
    sha256: 2868b0e61b7424174e9adef3cb87478329f8ab2075211ef28fe477f29e0e5c99
    folder: osqp_sources/lin_sys/direct/qdldl/qdldl_sources

build:
  number: 1
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [unix]
    - set "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}"   # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - setuptools_scm
    - pip
    - numpy
    - libosqp {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - qdldl-python
    - scipy
    - vs2015_runtime                 # [win]
  run_constrained:
    # since paradiso directly depends on the SO name, which was changed then
    - mkl >=2022.0                   # [win]

test:
  imports:
    - osqp
    - osqp.codegen
    - osqppurepy
  requires:
    # some of the tests need mkl-specific solvers
    - blas=*=mkl                     # [x86_64]
    # codegen interface requires compiler + cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                           # [unix]
    - cmake
    - cvxopt
    - pytest
    - setuptools
  commands:
    - python -m pytest --pyargs osqp

about:
  home: https://osqp.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/osqp/osqp-python

extra:
  recipe-maintainers:
    - djsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
